---
exclude_paths:
  - "**/*.spec.ts"
  - "**/*.test.ts"
  - "**/dist/**"
  - "**/node_modules/**"
  - "**/coverage/**"
  - "**/.nx/**"
  - "**/.nx-cache/**"
engines:
  eslint-8:
    exclude_paths:
      - "packages/typescript-preset/src/plugin.ts"